stages:
  - build
  - test

variables:
    DOCKER_DRIVER: overlay2
    GIT_SUBMODULE_STRATEGY: normal
    CTEST_OUTPUT_ON_FAILURE: 1

build-ubuntu:
  stage: build
  tags:
    - docker
  image: registry.iwstudio.hu/iws/ubuild:latest
  artifacts:
    paths:
      - build-ubuntu/bin
      - include
  variables:
    CC: clang
    CXX: clang++
  script:
    - mkdir build-ubuntu
    - cd build-ubuntu
    - cmake ../ -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --target $CI_PROJECT_NAME -- -j8

debug-build-ubuntu:
  stage: build
  tags:
    - docker
  image: registry.iwstudio.hu/iws/ubuild:latest
  artifacts:
    paths:
      - debug-build-ubuntu/bin
      - include
  variables:
    CC: clang
    CXX: clang++
  script:
    - mkdir debug-build-ubuntu
    - cd debug-build-ubuntu
    - cmake ../ -DCMAKE_BUILD_TYPE=Debug
    - cmake --build . --target $CI_PROJECT_NAME -- -j8

test-ubuntu:
  stage: test
  tags:
    - docker
  image: registry.iwstudio.hu/iws/ubuild:latest
  artifacts:
    paths:
      - test-build-ubuntu/ccov
  dependencies: [] # Disable artifact restoration
  variables:
    CC: clang
    CXX: clang++
  script:
    - mkdir test-build-ubuntu
    - cd test-build-ubuntu
    - cmake ../ -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON
    - cmake --build . --target check
    - cmake --build . --target ccov
    - cmake --build . --target ccov-report

release-test-ubuntu:
  stage: test
  tags:
    - docker
  image: registry.iwstudio.hu/iws/ubuild:latest
  dependencies: [] # Disable artifact restoration
  variables:
    CC: clang
    CXX: clang++
  script:
    - mkdir build
    - cd build
    - cmake ../ -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --target check

build-arch:
  stage: build
  tags:
    - docker
  image: registry.iwstudio.hu/iws/abuild:latest
  artifacts:
    paths:
      - build-arch/bin
      - include
  variables:
    CC: clang
    CXX: clang++
  script:
    - mkdir build-arch
    - cd build-arch
    - cmake ../ -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --target $CI_PROJECT_NAME -- -j8

debug-build-arch:
  stage: build
  tags:
    - docker
  image: registry.iwstudio.hu/iws/abuild:latest
  artifacts:
    paths:
      - debug-build-arch/bin
      - include
  variables:
    CC: clang
    CXX: clang++
  script:
    - mkdir debug-build-arch
    - cd debug-build-arch
    - cmake ../ -DCMAKE_BUILD_TYPE=Debug
    - cmake --build . --target $CI_PROJECT_NAME -- -j8

test-arch:
  stage: test
  tags:
    - docker
  image: registry.iwstudio.hu/iws/abuild:latest
  artifacts:
    paths:
      - test-build-arch/ccov
  dependencies: [] # Disable artifact restoration
  variables:
    CC: clang
    CXX: clang++
  script:
    - mkdir test-build-arch
    - cd test-build-arch
    - cmake ../ -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON
    - cmake --build . --target check
    - cmake --build . --target ccov
    - cmake --build . --target ccov-report

release-test-arch:
  stage: test
  tags:
    - docker
  image: registry.iwstudio.hu/iws/abuild:latest
  dependencies: [] # Disable artifact restoration
  variables:
    CC: clang
    CXX: clang++
  script:
    - mkdir build
    - cd build
    - cmake ../ -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --target check

build-msvc:
  stage: build
  tags:
    - msvc
  script:
    - call "%VCVARSALL%" x64
    - mkdir build-msvc
    - cd build-msvc
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..\
    - cmake --build . --target %CI_PROJECT_NAME%
    
debug-build-msvc:
  stage: build
  tags:
    - msvc
  script:
    - call "%VCVARSALL%" x64
    - mkdir debug-build-msvc
    - cd debug-build-msvc
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ..\
    - cmake --build . --target %CI_PROJECT_NAME%
    
test-msvc:
  stage: test
  tags:
    - msvc
  dependencies: [] # Disable artifact restoration
  script:
    - mkdir build
    - cd build
    - cmake ../ -DCMAKE_BUILD_TYPE=Debug # -DCODE_COVERAGE=ON # No code coverage on msvc yet
    - cmake --build . --target check

release-test-msvc:
  stage: test
  tags:
    - docker
  image: registry.iwstudio.hu/iws/abuild:latest
  dependencies: [] # Disable artifact restoration
  script:
    - call "%VCVARSALL%" x64
    - mkdir build
    - cd build
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ..\ # -DCODE_COVERAGE=ON # No code coverage on msvc yet
    - cmake --build . --target check
